services:
  dev:
    image: golang:1.22-alpine
    volumes:
      - .:/calq
    working_dir: /calq
    stdin_open: true
    tty: true

  releaser:
    image: goreleaser/goreleaser:v2.5.0-nightly
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
